# Generated by Django 4.0.5 on 2022-06-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiResponse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.CharField(max_length=20)),
                ("data", models.TextField()),
            ],
        ),
    ]
