# Generated by Django 4.0.5 on 2022-06-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celery_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apiresponse",
            name="data",
        ),
        migrations.RemoveField(
            model_name="apiresponse",
            name="message",
        ),
        migrations.AddField(
            model_name="apiresponse",
            name="apparentTemperature",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="apiresponse",
            name="cloudCover",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="apiresponse",
            name="dewPoint",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="apiresponse",
            name="humidity",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="apiresponse",
            name="icon",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="apiresponse",
            name="lat",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="apiresponse",
            name="lng",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="apiresponse",
            name="ozone",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="apiresponse",
            name="precipIntensity",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="apiresponse",
            name="pressure",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="apiresponse",
            name="summary",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="apiresponse",
            name="temperature",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="apiresponse",
            name="time",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="apiresponse",
            name="visibility",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="apiresponse",
            name="windBearing",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="apiresponse",
            name="windGust",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="apiresponse",
            name="windSpeed",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
