# Generated by Django 4.0.5 on 2022-06-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "celery_app",
            "0002_remove_apiresponse_data_remove_apiresponse_message_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="apiresponse",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
